spring.application.name=eats_hub_catalog
mongodb.host=localhost
mongodb.port=27018
mongodb.username=master
mongodb.password=master
mongodb.database=catalog
mongodb.authentication-database=admin
mongodb.maxPoolSize=100
mongodb.minPoolSize=10
mongodb.maxConnectionLifeTime=60000